"""Generic async repository with mandatory tenant scope.

Usage:
    class AlumnoRepository(BaseRepository[Alumno]):
        _model_cls = Alumno

        async def search_by_legajo(self, legajo: str) -> Alumno | None:
            stmt = self._stmt().where(Alumno.legajo == legajo)
            result = await self._session.execute(stmt)
            return result.scalar_one_or_none()
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Generic, Sequence, TypeVar

from sqlalchemy import Select, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.base import TenantScopedMixin

# TypeVar bounded to entities that have tenant_id
T = TypeVar("T", bound=TenantScopedMixin)


class BaseRepository(Generic[T]):
    """Async repository with mandatory tenant_id scoping.

    Every query generated by this repository automatically includes
    a WHERE tenant_id = :tenant_id clause, enforcing multi-tenant
    row-level isolation at the data access layer.

    Subclasses MUST set _model_cls to the specific model class.
    """

    _model_cls: type[T]

    def __init__(self, session: AsyncSession, tenant_id: uuid.UUID) -> None:
        self._session = session
        self._tenant_id = tenant_id

    # ── Query building ─────────────────────────────────────────────

    def _stmt(self) -> Select:
        """Base SELECT statement with tenant filter.

        Override in subclasses to add joins or default eager loading,
        but ALWAYS call super()._stmt() to keep the tenant filter.
        """
        return select(self._model_cls).where(
            self._model_cls.tenant_id == self._tenant_id  # type: ignore[arg-type]
        )

    def _exclude_deleted(self, stmt: Select) -> Select:
        """Appends filter to exclude soft-deleted rows if applicable."""
        if hasattr(self._model_cls, "deleted_at"):
            return stmt.where(self._model_cls.deleted_at.is_(None))  # type: ignore[arg-type]
        return stmt

    # ── CRUD operations ────────────────────────────────────────────

    async def get(self, id: uuid.UUID) -> T | None:
        """Retrieve a single record by id, scoped to tenant.

        Returns None if not found or if the record is soft-deleted.
        """
        stmt = self._exclude_deleted(self._stmt()).where(
            self._model_cls.id == id  # type: ignore[arg-type]
        )
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def list(self) -> Sequence[T]:
        """List all non-deleted records for this tenant."""
        stmt = self._exclude_deleted(self._stmt())
        result = await self._session.execute(stmt)
        return result.scalars().all()

    async def create(self, **kwargs: object) -> T:
        """Create a new record, automatically assigning tenant_id."""
        instance = self._model_cls(**kwargs, tenant_id=self._tenant_id)
        self._session.add(instance)
        await self._session.flush()
        return instance

    async def update(self, id: uuid.UUID, **kwargs: object) -> T | None:
        """Update fields of a record and return the updated instance.

        Only updates if the record exists, belongs to this tenant,
        and is not soft-deleted. Refreshes the instance after update
        so server-defaults (e.g. updated_at) are populated.
        """
        instance = await self.get(id)
        if instance is None:
            return None
        for field, value in kwargs.items():
            setattr(instance, field, value)
        await self._session.flush()
        await self._session.refresh(instance)
        return instance

    async def soft_delete(self, id: uuid.UUID) -> bool:
        """Soft-delete a record by setting deleted_at.

        Returns True if the record was found and deleted,
        False if not found or already deleted.
        """
        stmt = self._stmt().where(self._model_cls.id == id)  # type: ignore[arg-type]
        result = await self._session.execute(stmt)
        instance = result.scalar_one_or_none()
        if instance is None:
            return False
        instance.deleted_at = datetime.now(UTC)
        await self._session.flush()
        return True
